name: Backport changes

on:
  workflow_call:
    inputs:
      label-to-check-for:
        required: true
        type: string
      target-branch:
        required: true
        type: string

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR for backport label
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.12
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ inputs.label-to-check-for }}

      - name: See result
        run: echo "${{ steps.check_pr_labels.outputs.result }}"

      - name: Checkout repository
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: actions/checkout@v4
        with:
          # ensure the backport target branch is checked out, too
          fetch-depth: 0
          path: repo

      - if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: repo/.github/actions/backport
        with:
          GITHUB_TOKEN: ${{ github.token }}
