name: Backport changes to all maintenance branches
on:
 push:
  branches:
   - main
jobs:
  get-branches:
    runs-on: ubuntu-latest
    outputs:
      branches: "['5.0', '5.1', '5.2', '5.3', '5.4', '5.5']"
    steps:
      - run: exit 0

  backport-all:
    needs: get-branches
    strategy:
      fail-fast: true
      matrix:
        branch: ${{ fromJSON(needs.get-branches.outputs.branches) }}
    uses: ./.github/workflows/backport-workflow.yml
    with:
      label: '["backport to all versions"]'
      target-branch: v/${{ matrix.branch }}
    secrets: inherit
  backport-specified:
    needs: get-branches
    strategy:
      fail-fast: true
      matrix:
        branch: ${{ fromJSON(needs.get-branches.outputs.branches) }}
    uses: ./.github/workflows/backport-workflow.yml
    with:
      label: '["backport to ${{ matrix.branch }}"]'
      target-branch: v/${{ matrix.branch }}
    secrets: inherit
