name: Backport changes to all maintenance branches
on:
 push:
  branches:
   - main
jobs:
  backport:
    strategy:
      matrix:
        branch: ['5.0', '5.1', '5.2', '5.3', '5.4', '5.5']
    runs-on: ubuntu-latest
    steps:
        # TODO USE REMOTE DIRECTLY
      - name: checkout
        uses: actions/checkout@v4

      - name: Backport to all maintenance branches
        uses: ./.github/actions/backport
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: '["backport to all versions"]'
          target-branch: v/${{ matrix.branch }}

      - name: Backport to specified branch
        uses: ./.github/actions/backport
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          label: '["backport to ${{ matrix.branch }}"]'
          target-branch: v/${{ matrix.branch }}'
