name: Backport changes

on:
  workflow_call:
    inputs:
      label-to-check-for:
        required: true
        type: string
      target-branch:
        required: true
        type: string

jobs:
  backport:
    runs-on: ubuntu-latest

    steps:
      - name: Print accessible environment variables
        # if: runner.debug == '1'
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          printenv

      - name: Check PR for backport label
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.12
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ inputs.label-to-check-for }}

      - name: See result
        run: echo "${{ steps.check_pr_labels.outputs.result }}"

      - name: Checkout repository
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: actions/checkout@v4
        with:
          # ensure the backport target branch is checked out, too
          fetch-depth: 0
          path: repo

      - name: Checkout Backport tool
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        uses: actions/checkout@v4
        with:
          # TODO
          # repository: hazelcast/backport
          repository: JackPGreen/backport
          ref: make-labels-optional
          path: backport

      - name: Checkout maintenance branch and cherry-pick
        if: ${{ steps.check_pr_labels.outputs.result == 'true' }}
        working-directory: repo
        run: |
          ${RUNNER_DEBUG:+set -x}

          # Git metadata is required but not available out-of-the-box, inherit from the action
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          # Add "upstream" remote as checkout action doesn't include by default
          git remote add upstream "${{ github.event.repository.clone_url }}"
          git fetch --all

          backport_target_branch=upstream/"${{ inputs.target-branch }}"
          echo "::debug::Running backport script to backport "${GITHUB_SHA}" into \"${backport_target_branch}\""

          ${GITHUB_WORKSPACE}/backport/backport \
            "${GITHUB_SHA}" \
            "${backport_target_branch}" \
            --non-interactive \
            --omit-labels
        env:
          GH_TOKEN: ${{ github.token }}
