name: Forwardport changes to main
on:
  push:
    branches:
      - v/*
jobs:
  forwardport:
    uses: .github/actions/workflows/backport-workflow.yml@main
    with:
      label: '["forwardport to snapshot"]'
      target-branch: main
    secrets: inherit
