name: Forwardport changes to main
on:
  push:
    branches:
      - v/*
jobs:
  forwardport:
    # TODO RENAME
    uses: .github/actions/backport/action.yml@main
    with:
      label: '["forwardport to snapshot"]'
      target-branch: main
    secrets: inherit
