name: Forwardport changes to main
on:
  push:
    branches:
      - v/*
jobs:
  forwardport:
    runs-on: ubuntu-latest
    steps:
      # TODO USE REMOTE DIRECTLY
    - name: checkout
      uses: actions/checkout@v4

    - uses: ./.github/workflows/backport-workflow.yml
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        label: '["forwardport to snapshot"]'
        target-branch: main
